### ISSUE TITLE
Great! Comments

### ISSUE THREAD

**Issue by kalverra** [gonzalo-github/prj-rev-bwfs-tea-cozy#1]
https://github.com/gonzalo-github/prj-rev-bwfs-tea-cozy/blob/master/Tea_Cozy_Project/index.html#L9-L11

Nice organizational comments, I love the intent, but you don't need to make them so extreme in visibility. Just a simple ```<!--Header-->``` is fine. also the end versions are redundant and can actually hurt readability.

**Comment by gonzalo-github** [comment]
Thanks for the suggestion.
