### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by kalverra** [gonzalo-github/prj-rev-bwfs-tea-cozy#6]
**Grade**: Exceeds Expectations

**Summary**:
Well done here, your code is both functional and organized, meeting our spec. Both functionality and readability are about equally crucial in the programming world, and you seem to have paid attention to both. My concern is over your intensity of comments and spacing. The intent is good, but in this case, less is more. No need to make the comments so extreme or use them so often, keep them sparse and meaningful.

For future projects, try throwing in your own little bits of style to dress up the site and personalize it. It's good to practice design along with functional code, so use these templates as opportunity to try some things. http://www.webdesign-inspiration.com/web-designs/style/modern

**Comment by gonzalo-github** [comment]
Agree. I appreciate your suggestions that will help me make better websites.
